# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path
# Add Yarn node_modules folder to the asset load path.
Rails.application.config.assets.paths << Rails.root.join('node_modules')

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.
# Rails.application.config.assets.precompile += %w( admin.js admin.css )

Rails.application.config.assets.precompile += [
  "login.scss",
  "member.scss",
  "Login.js",
  "administration/users/Index.js",
  "accounting/accounting_codes/Index.js",
  "accounting/accounting_entries/Show.js",
  "accounting/year_end_closings/Index.js",
  "accounting/year_end_closings/Show.js",
  "administration/areas/Index.js",
  "administration/clusters/Index.js",
  "administration/branches/Index.js",
  "administration/centers/Index.js",
  "administration/announcements/Index.js",
  "administration/surveys/Index.js",
  "administration/surveys/Show.js",
  "administration/loan_products/Show.js",
  "administration/loan_products/Index.js",
  "accounting/BooksIndex.js",
  "billings/Index.js",
  "billings/Show.js",
  "savings_accounts/Show.js",
  "membership_payment_collections/Index.js",
  "membership_payment_collections/Show.js",
  "deposit_collections/Index.js",
  "deposit_collections/Show.js",
  "withdrawal_collections/Index.js",
  "withdrawal_collections/Show.js",
  "data_stores/personal_funds/Index.js",
  "data_stores/personal_funds/Show.js",
  "data_stores/branch_loans_stats/Show.js",
  "data_stores/branch_loans_stats/Index.js",
  "data_stores/accounting_entries_summaries/Index.js",
  "data_stores/soa_expenses/Index.js",
  "data_stores/soa_loans/Index.js",
  "data_stores/soa_funds/Index.js",
  "data_stores/watchlists/Index.js",
  "data_stores/repayment_rates/Index.js",
  "data_stores/branch_repayment_reports/Index.js",
  "data_stores/member_counts/Index.js",
  "data_stores/monthly_new_and_resigned/Index.js",
  "data_stores/monthly_incentives/Index.js",
  "data_stores/x_weeks_to_pay/Index.js",
  "data_stores/branch_with_centers_loans_stats/Show.js",
  "data_stores/branch_with_centers_loans_stats/Index.js",
  "members/Show.js",
  "members/Index.js",
  "members/SurveyAnswer.js",
  "members/member_shares/Show.js",
  "monthly_closing_collections/Index.js",
  "monthly_closing_collections/Show.js",
  "loans/Show.js",
  "MembersIndex.min.react.js",
  "MembersForm.min.react.js",
  "MembersFormResignation.min.react.js",
  "MemberAccountsSavingsIndex.min.react.js",
  "AccountingTrialBalance.min.react.js",
  "AccountingGeneralLedger.min.react.js",
  "AccountingEntryForm.min.react.js",
  "BillingUI.min.react.js",
  "SurveyUI.min.react.js",
  "SurveyQuestionUI.min.react.js",
  "MembershipPaymentCollectionUI.min.react.js",
  "DepositCollectionUI.min.react.js",
  "WithdrawalCollectionUI.min.react.js",
  "BranchManager.min.react.js",
  "BranchLoanProductStats.min.react.js",
  "LoanApplicationForm.min.react.js",
  "LoanAccountingEntry.min.react.js",
  "MemberSurveyAnswerUI.min.react.js",
  "DashboardMain.min.react.js",
  "BranchRepaymentReportShow.min.react.js",
  "PersonalFundsShow.min.react.js",
  "XWeeksToPayShow.min.react.js",
  "SoaExpensesShow.min.react.js",
  "SoaLoansShow.min.react.js",
  "SoaFundsShow.min.react.js",
  "WatchlistsShow.min.react.js",
  "RepaymentRatesShow.min.react.js",
  "MonthlyClosingCollectionShow.min.react.js",
  "MonitoringAccountingEntrySubsidiaryBalancing.min.react.js",
  "MonitoringAccountingEntryPrecision.min.react.js",
  "claims/Index.js",
  "claims_form.js",
  "claims.js",
  "exports/Exports.js",
  "MemberAccountInsuranceStatus.min.react.js",
  "member_account_validation/Index.js",
  "member_account_validation/MemberAccountValidations.js",
  "member_account_validation/MemberAccountValidationForm.js",
  "member_account_validation/ValidationsReport.js",
  "clip_claims/Index.js",
  "clip_claims.js",
  "clip_claims_form.js",
  "Seriatim.js"
]
