company_name: "KASAGANA-KA CREDIT AND SAVINGS COOPERATIVE"
company_address: "5 Don Francisco St, Don Enrique Heights, Quezon Cty"

defaults:
  insurance_deposits:
    - 
      account_subtype: "Life Insurance Fund"
      amount: 15.00
    -
      account_subtype: "Retirement Fund"
      amount: 5.00

branch_billing_accounting_codes:
  -
    branch_id: "06c2fd58-e93b-4066-afd2-f3fe3a7d4f1c"
    cash_in_bank_accounting_code_id: "afbb24a0-b1ef-4ce8-8bff-40388e525497"
    withdraw_payment_accounting_code_id: "afbb24a0-b1ef-4ce8-8bff-40388e525497"
  -
    branch_id: "125681b8-9826-4b01-9dd3-11a6f2beebbd"
    cash_in_bank_accounting_code_id:
    withdraw_payment_accounting_code_id:

loan_product_accounting_codes:
  -
    loan_product_id: "15a9ac0b-ef51-4470-88a3-bab8a7a72557"                         # K-Kabuhayan
    receivable_accounting_code_id: "9b494af8-14fd-46b4-ab7c-70fa37dbe0ab"
    interest_receivable_accounting_code_id: "01d3dd16-a89a-46be-94c0-60b8bcc0033d"
  -
    loan_product_id: "e78c361b-d52a-4f49-81b9-ec0c2182b8ff"                         # K-Bahay W1
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "6ac70669-21ee-4ff5-86b3-053e71b0c84d"                         # K-Bahay W2
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "abea45ce-a02f-4954-8547-55b091cb0ef3"                         # K-Bahay W3
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "cc4601fe-b4e6-4e9f-af29-edd7570141a7"                         # K-Benepisyo W1
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "7edfde52-71fe-4249-b96a-2f316d504425"                         # K-Benepisyo W2
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "0d03a959-c397-4ee3-a878-1386dcaa302b"                         # K-Edukasyon
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "7edfde52-71fe-4249-b96a-2f316d504425"                         # K-Edukasyon W2
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "a2c7008c-e45d-4c24-be72-6f66a1bbec9e"                         # K-Kalamidad
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "f7a76bf3-cce4-48fc-b9bc-13e9b5c4c6c8"                         # K-Kalusugan W1
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "bf5671ed-8473-4db4-980f-6ba7a2fb7163"                         # K-Kalusugan W2
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "10d28981-1132-4ea8-9fbd-b14e4348efd7"                         # K-Kalusugan W3
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "b13f34e5-abbd-4899-922c-dbb77879bd51"                         # K-Kalusugan W4
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
  -
    loan_product_id: "2f2329c5-6866-4a71-8328-860fe8c095dc"                         # K-Kalusugan W5
    receivable_accounting_code_id: ""
   -
    loan_product_id: "f9b2ffd9-ad4d-4cf7-9de6-b81016c474e9"                         # K-Kalusugan W6
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
   -
    loan_product_id: "9718d92b-f71f-40ed-be52-0a9e1f3e2f47"                         # K-Kalusugan W7
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
   -
    loan_product_id: "93cc8b30-f76a-4030-a392-300a96b00afe"                         # K-Kasal
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
   -
    loan_product_id: "114a803c-1703-4893-ad62-359c468edf25"                         # K-Kasangkapan
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
   -
    loan_product_id: "d1233493-0300-40b7-bb00-bbb2f502c398"                         # K-Manggagawa
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
   -
    loan_product_id: "e5830d02-2608-413a-b023-ca62b4285c0a"                         # K-NHA W1
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
   -
    loan_product_id: "84ef3a7b-9364-4012-a22d-b5ec8d242934"                         # K-NHA W2
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
   -
    loan_product_id: "9381e609-0df7-472d-9010-dcd765dd31b2"                         # K-PWD
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
   -
    loan_product_id: "2c9d23d5-9c06-4084-9196-8843fb32cd7d"                         # K-TODA
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
   -
    loan_product_id: "3a092aa7-ded5-48fe-8f11-3052c9d59a24"                         # K-TRABAHO
    receivable_accounting_code_id: ""
    interest_receivable_accounting_code_id: ""
