class ClaimAttachmentFile < ApplicationRecord
  FILE_NAMES = [ 
  	"AFFIDAVIT OF COHABITATION",
  	"AUTHORIZATION LETTER",
  	"BIRTH CERTIFICATE",
  	"BLIP APPLICATION FORM",
  	"BUGDET REQUEST",
  	"CENOMAR",
  	"CENTER ENDORSEMENT LETTER",
  	"CLIP APPLICATIOM FORM",
  	"DEATH CERTIFICATE",
  	"FINAL GRADE LAST SY/SEMESTER",
  	"HIIP APPLICATION FORM",
  	"HOSPITAL BILLING",
  	"ID OF CB",
  	"ID OF CLAIMANT",
  	"ID OF AUTHORIZED PERSON",
  	"IMAGE/PICTURE/OF ATM OR ACCOUNT",
  	"INSURANCE PAYMENT LEDGER",
  	"KMBA NOTICE ALL IN 1",
  	"LOAN LEDGER",
  	"MARRIAGE CONTRACT",
  	"MEDICAL CERTIFICATE",
  	"POLICE REPORT/BARANGAY BLOTTER",
  	"PROOF OF CONFINEMENT",
  	"PROOF OF DEATH",
  	"PROOF OF ENROLLMENT OR ANY KIND",
  	"RECEIPT/OR FOR REIMBURSEMENT",
  	"SOM ENDORSEMENT LETTER",
  	"WAIVER OF DESIGNATED BENEFICIARY",
  	"OTHERS"
  ]

  belongs_to :claim

  # has_one_attached :file

  has_many_attached :files

  # validates :file_name, presence: true, inclusion: { in: FILE_NAMES }
end
