class ClaimAttachmentFile < ApplicationRecord
  FILE_NAMES = [ 
  	"AFFIDAVIT OF COHABITATION",
  	"AUTHORIZATION LETTER",
  	"BIRTHCERTIFICATE",
  	"BLIP APPLICATION FORM",
  	"BUGDET REQUEST",
  	"CENOMAR",
  	"CENTER ENDORSEMENT LETTER",
  	"CLIP APPLICATIOM FORM",
  	"DEATHCERTIFICATE",
  	"HIIP APPLICATION FORM",
  	"HOSPITAL BILLING",
  	"ID OF CB",
  	"ID OF CLAIMANT",
  	"ID OF AUTHORIZE PERSON",
  	"IMAGE/PICTURE/OF ATM OR ACCOUNT",
  	"INSURANCE PAYMENT LEDGER",
  	"KMBA NOTICE ALL IN 1",
  	"MARRIAGE CONTRACT",
  	"MEDICAL CERTIFICATE",
  	"POLICE REPORT/BARANGAY BLOTTER",
  	"PROOF OF CONFINEMENT",
  	"PROOF OF DEATH",
  	"RECEIPT/OR FOR REIMBURSEMENT",
  	"SOM ENDORSEMENT LETTER",
  	"WAIVER OF DESIGNATED BENEFICIARY",
  	"OTHERS"
  ]

  belongs_to :claim

  has_one_attached :file

  validates :file_name, presence: true, inclusion: { in: FILE_NAMES }
end
