class ClaimAttachmentFile < ApplicationRecord
  FILE_NAMES = [ 
  	"BLIP APPLICATION FORM",
  	"CLIP APPLICATIOM FORM",
  	"HIIP APPLICATION FORM",
  	"MARRIAGE CONTRACT",
  	"CENOMAR",
  	"BIRTHCERTIFICATE",
  	"AFFIDAVIT OF COHABITATION",
  	"ID OF CB",
  	"ID OF CLAIMANT",
  	"ID OF AUTHORIZE PERSON",
  	"IMAGE/PICTURE/OF ATM OR ACCOUNT",
  	"PROOF OF DEATH",
  	"DEATHCERTIFICATE",
  	"KMBA NOTICE ALL IN 1",
  	"SOM ENDORSEMENT LETTER",
  	"CENTER ENDORSEMENT LETTER",
  	"POLICE REPORT/BARANGAY BLOTTER",
  	"PROOF OF CONFINEMENT",
  	"HOSPITAL BILLING",
  	"RECEIPT/OR FOR REIMBURSEMENT",
  	"MEDICAL CERTIFICATE",
  	"BUGDET REQUEST",
  	"OTHERS"
  ]

  belongs_to :claim

  has_one_attached :file

  validates :file_name, presence: true, inclusion: { in: FILE_NAMES }
end
